### ISSUE TITLE
Startup crash 

### ISSUE THREAD

**Issue by wormzjl** [marcin212/Zetta-Industries#39]
http://pastebin.com/T1Cs45iN

**Comment by marcin212** [comment]
update forestry or downgrade ZI to http://ci.bymarcin.com/job/Zetta-Industries/105/artifact/build/libs/zettaindustries-1.1-105.jar

**Comment by mpevner** [comment]
Oddly enough, with ZI-114, I am having crashes with forestry 4.2.(2~4) with a similar reason. It does work with 4.2.0 though.

`java.lang.NoClassDefFoundError: forestry/core/config/ForestryItem
	at com.bymarcin.zettaindustries.mods.ecatalogue.ECatalogueMod.postInit(ECatalogueMod.java:37) ~[ECatalogueMod.class:?]`

http://pastebin.com/LgnCLg4s

**Comment by marcin212** [comment]
@mpevner You have zettaindustries-1.1-105 (pastebin line 288). 
ZI-105 == Forestry 3.6.X 
ZI-114 == Forestry  4.2.X

**Comment by mpevner** [comment]
Sorry, wrong crash report.

http://pastebin.com/VVvH0RKn

Though, looking better, this actually appears to be an Opencomputers related crash? I can refile in a new ticket if you'd like.

**Comment by marcin212** [comment]
@mpevner special version http://cloud.bymarcin.com/index.php/s/LtNjEGDOGBleqsZ/download

**Comment by mpevner** [comment]
Works awesome! All related mods are verified at the latest version as well with this.

**Comment by marcin212** [comment]
last unstable on jenkins is for OC 1.6

**Comment by mpevner** [comment]
Hmn, I guess OC updated some of its API code then. Thanks for the special version! ZI is a Wonderful addon to have.
